from django.conf.urls import patterns, include, url

urlpatterns = patterns('yighub.views',
    url(r'^$', 'home'),
    url(r'^home/$', 'home', name='home'),
    url(r'^home/page/(?P<current_page>\d+)/$', 'home'),
    url(r'^board/create/$', 'create_board'),
    url(r'^board/(?P<board_number>\d+)/$', 'board', name='board'),
    url(r'^board/(?P<board_number>\d+)/page/(?P<current_page>\d+)/$', 'board'),
    url(r'^board/(?P<board_number>\d+)/entry/create/$', 'create'),
    url(r'^entry/(?P<entry_id>\d+)/$', 'read', name='read') ,
    url(r'^entry/create/$', 'create', name='create'),
    url(r'^entry/(?P<entry_id>\d+)/edit/$', 'edit', name='edit'),
    url(r'^entry/(?P<entry_id>\d+)/delete/$', 'delete', name='delete'),
    url(r'^entry/(?P<entry_id>\d+)/reply/$', 'reply', name='reply'),
    url(r'^entry/(?P<entry_id>\d+)/recommend/$', 'recommend', name='recommend'),
    url(r'^entry/(?P<entry_id>\d+)/comment/$', 'comment', name='comment'),
    url(r'^entry/(?P<entry_id>\d+)/comment/(?P<comment_id>\d+)/reply/$', 'reply_comment', name='reply_comment'),
    url(r'^entry/(?P<entry_id>\d+)/comment/(?P<comment_id>\d+)/recommend/$', 'recommend_comment', name='recommend_comment'),
    url(r'^intro/(?P<intro_name>\w+)/(?P<current_page>\d+)/$', 'intro'),
    url(r'^intro/(?P<intro_name>\w+)/create/$', 'create_intro'),
    url(r'^join/$', 'join', name='join'),
    url(r'^login/$', 'login', name='login'),
    url(r'^login_check/$', 'login_check', name='login_check'),
    url(r'^logout/$', 'logout', name='logout'),
    url(r'^letter/list/$', 'letters'),
    url(r'^letter/send/$', 'send'),
    url(r'^letter/receive/(?P<letter_id>\d+)/$', 'receive'),
    url(r'^letter/receive/(?P<letter_id>\d+)/download/$', 'download_letter'),
    url(r'^memo/create/$', 'create_memo'),
    url(r'^download/(?P<file_id>\d+)/$', 'download', name='download'),
    
)
