# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-05 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yighub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicboard',
            name='active_fund',
            field=models.BooleanField(default=False),
        ),
    ]
